"""Tests for find_latest_csv, _fn_to_key, _discover_slot_map, and build_generated_js."""

import re
import textwrap
from pathlib import Path
from unittest.mock import MagicMock, patch

import pandas as pd
import pytest

from page_creator.generate_charts import (
    _PATTERN,
    _PREFIX_MAP,
    build_generated_js,
    _fn_to_key,
)

# ── Helpers ───────────────────────────────────────────────────────────────────


def _make_csv(path: Path, content: str = "col\nval\n") -> Path:
    path.write_text(content, encoding="utf-8")
    return path


# ── _fn_to_key ────────────────────────────────────────────────────────────────


class TestFnToKey:

    def _mock_fn(self, name: str, module: str) -> MagicMock:
        fn = MagicMock()
        fn.__name__ = name
        fn.__module__ = module
        return fn

    def test_chart_function(self):
        fn = self._mock_fn(
            "generate_chart_outcomes", "page_creator.partials.charts.outcomes"
        )
        assert _fn_to_key(fn) == "chart_outcomes.html"

    def test_list_function(self):
        fn = self._mock_fn(
            "generate_collection_ongoing",
            "page_creator.partials.lists.collection_ongoing",
        )
        assert _fn_to_key(fn) == "list_collection_ongoing.html"

    def test_counter_function_no_prefix(self):
        fn = self._mock_fn("generate_kpi_row", "page_creator.partials.counters.kpi_row")
        assert _fn_to_key(fn) == "kpi_row.html"

    def test_date_stamp_function_no_prefix(self):
        fn = self._mock_fn(
            "generate_last_data_update",
            "page_creator.partials.date_stamp.last_data_update",
        )
        assert _fn_to_key(fn) == "last_data_update.html"

    def test_raises_on_unknown_subdir(self):
        fn = self._mock_fn(
            "generate_something", "page_creator.partials.unknown.something"
        )
        with pytest.raises(ValueError, match="not registered in _PREFIX_MAP"):
            _fn_to_key(fn)

    def test_raises_on_wrong_naming_pattern(self):
        fn = self._mock_fn("build_kpi_row", "page_creator.partials.counters.kpi_row")
        with pytest.raises(ValueError, match="naming pattern"):
            _fn_to_key(fn)

    def test_chart_prefix_not_duplicated(self):
        fn = self._mock_fn(
            "generate_chart_ecis_year", "page_creator.partials.charts.ecis_year"
        )
        result = _fn_to_key(fn)
        assert result == "chart_ecis_year.html"
        assert "chart_chart" not in result

    def test_list_prefix_not_duplicated(self):
        fn = self._mock_fn(
            "generate_law_passed", "page_creator.partials.lists.law_passed"
        )
        result = _fn_to_key(fn)
        assert result == "list_law_passed.html"
        assert "list_list" not in result


# ── build_generated_js ───────────────────────────────────────────────────────


class TestBuildGeneratedJs:

    def test_returns_string(self):
        result = build_generated_js({"chart_outcomes.html": "chart-outcomes-slot"})
        assert isinstance(result, str)

    def test_contains_auto_generated_comment(self):
        result = build_generated_js({})
        assert (
            "// AUTO-GENERATED by page_creator/generate_charts.py — do not edit manually."
            in result
        )

    def test_contains_const_declaration(self):
        result = build_generated_js({})
        assert "const GENERATED_PARTIALS = [" in result

    def test_contains_filename_entry(self):
        result = build_generated_js({"chart_outcomes.html": "chart-outcomes-slot"})
        assert (
            '["generated/partials/chart_outcomes.html", "chart-outcomes-slot"],'
            in result
        )

    def test_contains_slot_id_entry(self):
        result = build_generated_js({"chart_outcomes.html": "chart-outcomes-slot"})
        assert '"chart-outcomes-slot"' in result
        assert 'id="chart-outcomes-slot"' not in result

    def test_multiple_entries_all_present(self):
        slot_map = {
            "chart_outcomes.html": "chart-outcomes-slot",
            "list_law_passed.html": "list-law-passed-slot",
            "kpi_row.html": "kpi-row-slot",
        }
        result = build_generated_js(slot_map)
        for filename, slot_id in slot_map.items():
            assert f'["generated/partials/{filename}", "{slot_id}"],' in result

    def test_empty_slot_map_produces_empty_array(self):
        result = build_generated_js({})
        assert "const GENERATED_PARTIALS = [\n\n];" in result

    def test_entries_are_arrays_of_two_strings(self):
        result = build_generated_js({"kpi_row.html": "kpi-row-slot"})
        assert '["generated/partials/kpi_row.html", "kpi-row-slot"],' in result
