#!/usr/bin/env python3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from page_creator.partials.charts import (
    generate_chart_outcomes,
    generate_chart_signatures_cohorts,
    generate_chart_ecis_year,
    generate_chart_top_10_signatures,
)
from page_creator.partials.counters import generate_kpi_row
from page_creator.partials.lists import generate_currently_open

CSV_PATH = Path(__file__).parent / "data" / "initiatives.csv"
PARTIALS_DIR = Path(__file__).parent / "partials"
OUT_DIR = Path(__file__).parent.parent / "page_to_export" / "partials"
GENERATED_JS = (
    Path(__file__).parent.parent
    / "page_to_export"
    / "script"
    / "elements"
    / "generated.js"
)

_PREFIX_MAP: dict[str, str] = {
    "counters": "",
    "lists": "list",
    "charts": "chart",
}

_EXCLUDE = frozenset({"__init__.py", "helpers.py", "utils.py"})


def _discover_slot_map() -> dict[str, str]:
    slot_map: dict[str, str] = {}
    for subdir, prefix in _PREFIX_MAP.items():
        for py_file in sorted((PARTIALS_DIR / subdir).glob("*.py")):
            if py_file.name in _EXCLUDE:
                continue
            stem = py_file.stem
            stem_dashes = stem.replace("_", "-")
            html_name = f"{prefix}_{stem}.html" if prefix else f"{stem}.html"
            slot_id = (
                f"{prefix}-{stem_dashes}-slot" if prefix else f"{stem_dashes}-slot"
            )
            slot_map[html_name] = slot_id
    return slot_map


def _build_generated_js(slot_map: dict[str, str]) -> str:
    entries = "\n".join(
        f'    ["partials/{filename}", "{slot_id}"],'
        for filename, slot_id in slot_map.items()
    )
    return (
        "// AUTO-GENERATED by page_creator/generate_charts.py — do not edit manually.\n"
        f"const GENERATED_PARTIALS = [\n{entries}\n];\n"
    )


def main() -> None:
    df = pd.read_csv(CSV_PATH)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_JS.parent.mkdir(parents=True, exist_ok=True)

    slot_map = _discover_slot_map()

    partials: dict[str, str] = {
        "kpi_row.html": generate_kpi_row(df),
        "list_currently_open.html": generate_currently_open(df),
        "chart_outcomes.html": generate_chart_outcomes(df),
        "chart_signatures_cohorts.html": generate_chart_signatures_cohorts(df),
        "chart_ecis_year.html": generate_chart_ecis_year(df),
        "chart_top_10_signatures.html": generate_chart_top_10_signatures(df),
    }

    for filename, html in partials.items():
        path = OUT_DIR / filename
        path.write_text(html, encoding="utf-8")
        print(f"  wrote {path}  ({path.stat().st_size:,} bytes)")

    GENERATED_JS.write_text(_build_generated_js(slot_map), encoding="utf-8")
    print(f"  wrote {GENERATED_JS}  ({GENERATED_JS.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
