#!/usr/bin/env python3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from page_creator.partials.charts import (
    generate_chart_top_10_signatures,
    generate_chart_outcomes,
    generate_chart_signatures_cohorts,
)
from page_creator.partials.counters import generate_kpi_row
from page_creator.partials.lists import generate_currently_open

CSV_PATH = Path(__file__).parent / "data" / "initiatives.csv"
OUT_DIR = Path(__file__).parent.parent / "page_to_export" / "partials"
GENERATED_JS = (
    Path(__file__).parent.parent
    / "page_to_export"
    / "script"
    / "elements"
    / "generated.js"
)

# Maps partial filename → DOM slot id.
# Static partials (header, footer) live in elements/static.js — not here.
SLOT_MAP: dict[str, str] = {
    "kpi_row.html": "kpi-slot",
    "chart_top_10_signatures.html": "chart1-slot",
    "chart_outcomes.html": "chart-initiatives-status-slot",
    "chart_signatures_cohorts.html": "chart-signatures-count-slot",
    "list_currently_open.html": "currently-open",
}


def _build_generated_js(slot_map: dict[str, str]) -> str:
    entries = "\n".join(
        f'    ["partials/{filename}", "{slot_id}"],'
        for filename, slot_id in slot_map.items()
    )
    return (
        "// AUTO-GENERATED by page_creator/generate_charts.py — do not edit manually.\n"
        f"const GENERATED_PARTIALS = [\n{entries}\n];\n"
    )


def main() -> None:
    df = pd.read_csv(CSV_PATH)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_JS.parent.mkdir(parents=True, exist_ok=True)

    partials: dict[str, str] = {
        "kpi_row.html": generate_kpi_row(df),
        "chart_top_10_signatures.html": generate_chart_top_10_signatures(df),
        "chart_outcomes.html": generate_chart_outcomes(df),
        "chart_signatures_cohorts.html": generate_chart_signatures_cohorts(df),
        "list_currently_open.html": generate_currently_open(df),
    }

    for filename, html in partials.items():
        path = OUT_DIR / filename
        path.write_text(html, encoding="utf-8")
        print(f"  wrote {path}  ({path.stat().st_size:,} bytes)")

    GENERATED_JS.write_text(_build_generated_js(SLOT_MAP), encoding="utf-8")
    print(f"  wrote {GENERATED_JS}  ({GENERATED_JS.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
