"""Registry of partial generators and slot-map utilities for the ECI dashboard."""

import re

from page_creator.paths import PARTIALS_DIR, OUT_DIR, GENERATED_JS
from page_creator.partials.charts import (
    generate_chart_outcomes,
    generate_chart_signatures_cohorts,
    generate_chart_ecis_year,
    generate_chart_signatures_map,
    generate_chart_top_10_signatures,
    generate_chart_bubble_finance_plot,
)
from page_creator.partials.counters import generate_kpi_row
from page_creator.partials.lists import (
    generate_collection_ongoing,
    generate_got_response,
    generate_law_passed,
    generate_reached_signatures,
    generate_total_initiatives,
    generate_awaiting_response,
    generate_collection_unsuccessful,
    generate_commission_engaged,
    generate_rejected_legislation,
    generate_withdrawn,
)

_PREFIX_MAP: dict[str, str] = {
    "counters": "",
    "lists": "list",
    "charts": "chart",
    "date_stamp": "",
}

_EXCLUDE = frozenset({"__init__.py", "helpers.py", "utils.py"})

_GENERATORS = [
    generate_kpi_row,
    generate_collection_ongoing,
    generate_chart_outcomes,
    generate_chart_signatures_cohorts,
    generate_chart_ecis_year,
    generate_chart_signatures_map,
    generate_chart_top_10_signatures,
    generate_chart_bubble_finance_plot,
    generate_got_response,
    generate_law_passed,
    generate_reached_signatures,
    generate_total_initiatives,
    generate_awaiting_response,
    generate_collection_unsuccessful,
    generate_commission_engaged,
    generate_rejected_legislation,
    generate_withdrawn,
]

_PATTERN = re.compile(r"^generate_(.+)$")


def _fn_to_key(fn) -> str:
    """Derive an HTML filename from a generator function using its module path.

    Examples:
        generate_chart_outcomes     (charts/)   → chart_outcomes.html
        generate_collection_ongoing (lists/)    → list_collection_ongoing.html
        generate_kpi_row            (counters/) → kpi_row.html
    """
    subdir = fn.__module__.split(".")[-2]
    if subdir not in _PREFIX_MAP:
        raise ValueError(
            f"Function '{fn.__name__}' lives in module '{fn.__module__}'; "
            f"subdir '{subdir}' is not registered in _PREFIX_MAP "
            f"(known subdirs: {list(_PREFIX_MAP)})."
        )
    prefix = _PREFIX_MAP[subdir]

    match = _PATTERN.fullmatch(fn.__name__)
    if not match:
        raise ValueError(
            f"Generator '{fn.__name__}' does not follow the required "
            "'generate_{element_name}' naming pattern."
        )
    raw = match.group(1)
    element = raw.removeprefix(f"{prefix}_") if prefix else raw

    return f"{prefix}_{element}.html" if prefix else f"{element}.html"


def discover_slot_map() -> dict[str, str]:
    """Scan the partials directory and return a mapping of HTML filename → slot id."""
    slot_map: dict[str, str] = {}
    for subdir, prefix in _PREFIX_MAP.items():
        for py_file in sorted((PARTIALS_DIR / subdir).glob("*.py")):
            if py_file.name in _EXCLUDE:
                continue
            stem = py_file.stem
            stem_dashes = stem.replace("_", "-")
            html_name = f"{prefix}_{stem}.html" if prefix else f"{stem}.html"
            slot_id = (
                f"{prefix}-{stem_dashes}-slot" if prefix else f"{stem_dashes}-slot"
            )
            slot_map[html_name] = slot_id
    return slot_map


def build_generated_js(slot_map: dict[str, str]) -> str:
    """Render the JS ``GENERATED_PARTIALS`` constant from a slot map."""
    entries = "\n".join(
        f'    ["generated/partials/{filename}", "{slot_id}"],'
        for filename, slot_id in slot_map.items()
    )

    return (
        "// AUTO-GENERATED by page_creator/generate_charts.py — do not edit manually.\n"
        f"const GENERATED_PARTIALS = [\n{entries}\n];\n"
    )


def generate_partials_map(df) -> dict[str, str]:
    """Build a mapping of HTML filenames to rendered HTML strings for all registered generators."""
    return {_fn_to_key(fn): fn(df) for fn in _GENERATORS}
