// AUTO-GENERATED by page_creator/generate_charts.py — do not edit manually.
const GENERATED_PARTIALS = [
    ["partials/kpi_row.html", "kpi-slot"],
    ["partials/chart_top_10_signatures.html", "chart1-slot"],
    ["partials/chart_outcomes.html", "chart-initiatives-status-slot"],
    ["partials/chart_signatures_cohorts.html", "chart-signatures-count-slot"],
    ["partials/list_currently_open.html", "currently-open"],
];
