[project]
name = "eci-data-pipeline"
version = "0.1.0"
description = "Web scraping pipeline for European Citizens' Initiatives (ECI) data."
readme = "../README.ECI_initiatives.md"
requires-python = ">=3.10"

dependencies = [
  "selenium==4.35.0",
  "beautifulsoup4==4.13.5",
  "pydantic==2.12.5",
  "html5lib==1.1",
]

[project.scripts]
eci-scrape-initiatives = "data_pipeline.scraper.initiatives.__main__:scrape_eci_initiatives"
eci-scrape-responses = "data_pipeline.scraper.responses.main:scrape_commission_responses"
eci-scrape-followup = "data_pipeline.scraper.responses_followup_website.main:scrape_followup_websites"

[tool.setuptools]
package-dir = {"" = ".."}  # look for packages in the parent of data_pipeline/

[tool.setuptools.packages.find]
where = [".."]
include = ["data_pipeline*"]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
